### ISSUE TITLE
Archive notes instead of deleting them

### ISSUE THREAD

**Issue by loopified** [Malabarba/audio-notes-mode#5]
Nice package!

I believe deleting is too radical a thing to do nowadays where memory is cheap and audio files with low/medium quality for voice notes can be really small. Even if that is the desired behavior, it would probably be better to be an opt-in feature.

Isn't it better to default to archiving, like Orgmode? Generate a folder at a default directory and use that?

**Comment by Malabarba** [comment]
Yes, that sounds reasonable. Would you like to give it a try?
